import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabaseClient";
import { useRouter } from "next/router";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Profile() {
  const [employee, setEmployee] = useState(null);
  const router = useRouter();
  const [attendanceCount, setAttendanceCount] = useState(0);
  const [leaveCount, setLeaveCount] = useState(0);
  const [salaryCount, setSalaryCount] = useState(0);

  const generateBioData = async () => {
    if (!employee) {
      alert("Employee data not loaded");
      return;
    }

    const pdf = new jsPDF();

    // Company Header
    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, 210, 35, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("ABC CORPORATION LTD.", 105, 22, { align: "center" });
    
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "normal");
    pdf.text("Employee Bio Data", 105, 42, { align: "center" });

    // Employee Details
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text("PERSONAL INFORMATION", 15, 55);
    
    const details = [
      ["Full Name", employee.full_name || "N/A"],
      ["Email Address", employee.email || "N/A"],
      ["Phone Number", employee.phone || "N/A"],
      ["Employee ID", `EMP-${employee.id?.slice(0, 6).toUpperCase() || "N/A"}`],
      ["Department", employee?.departments?.name || "N/A"],
      ["Job Title", employee.job_title || "N/A"],
      ["Join Date", employee.join_date ? new Date(employee.join_date).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      }) : "N/A"],
      ["Status", "Active"],
    ];

    autoTable(pdf, {
      startY: 60,
      head: [["Field", "Details"]],
      body: details,
      headStyles: {
        fillColor: [37, 99, 235],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      margin: { left: 15, right: 15 },
    });

    const finalY = pdf.lastAutoTable.finalY + 15;
    
    // Attendance Summary
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text("ATTENDANCE SUMMARY", 15, finalY);
    
    autoTable(pdf, {
      startY: finalY + 5,
      body: [
        ["Total Days Present", attendanceCount.toString()],
        ["Approved Leaves", leaveCount.toString()],
      ],
      theme: "plain",
      styles: {
        fontSize: 10,
      },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 60 },
        1: { cellWidth: 30 },
      },
      margin: { left: 15 },
    });

    // Footer
    pdf.setTextColor(128, 128, 128);
    pdf.setFontSize(8);
    pdf.text("This is an official document generated by ABC CORPORATION", 105, finalY + 50, { align: "center" });
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, finalY + 58, { align: "center" });

    pdf.save(`Employee_Biodata_${employee.full_name}.pdf`);
  };

  useEffect(() => {
    const loadEmployee = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;

      const { data, error } = await supabase
        .from("employees")
        .select(`
          *,
          departments(name)
        `)
        .eq("email", session.user.email)
        .single();

      if (error) {
        console.error("EMP ERROR:", error);
        return;
      }

      setEmployee(data);

      // Attendance Count
      const { data: attendanceData, error: attError } = await supabase
        .from("attendance")
        .select("*")
        .eq("employee_id", data.id)
        .eq("status", "Present");

      if (!attError) {
        setAttendanceCount(attendanceData?.length || 0);
      }

      // Leaves Count
      const { data: leaveData, error: leaveError } = await supabase
        .from("leaves")
        .select("*")
        .eq("employee_id", data.id)
        .eq("status", "Approved");

      if (!leaveError) {
        setLeaveCount(leaveData?.length || 0);
      }

      // Salary Count
      const { data: salaryData, error: salaryError } = await supabase
        .from("salaries")
        .select("*")
        .eq("employee_id", data.id);

      if (!salaryError) {
        setSalaryCount(salaryData?.length || 0);
      }
    };

    loadEmployee();
  }, []);

  return (
    <div className="profile-page">
      {/* Header */}
      <div className="header">
        <div>
          <h1 className="page-title">Employee Profile</h1>
          <p className="page-subtitle">View and manage your personal information</p>
        </div>
        <button className="back-btn" onClick={() => router.push("/employees/dashboard")}>
          <svg className="btn-icon" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd" />
          </svg>
          Dashboard
        </button>
      </div>

      {/* Main Content */}
      <div className="profile-container">
        {/* Left Column - Profile Card */}
        <div className="profile-card">
          <div className="avatar-section">
            <div className="avatar">
              {employee?.full_name?.charAt(0) || 'U'}
            </div>
          </div>
          
          <h2 className="name">{employee?.full_name || "N/A"}</h2>
          <p className="role">{employee?.job_title || "Employee"}</p>
          
          <div className="info-items">
            <div className="info-item">
              <span className="info-label">Employee ID</span>
              <span className="info-value">{employee ? `EMP-${employee.id?.slice(0, 6).toUpperCase()}` : "N/A"}</span>
            </div>
            <div className="info-item">
              <span className="info-label">Status</span>
              <span className="info-value status-active">
                <span className="status-dot"></span>
                Active
              </span>
            </div>
            <div className="info-item">
              <span className="info-label">Department</span>
              <span className="info-value">{employee?.departments?.name || "N/A"}</span>
            </div>
          </div>

          <div className="stats-line">
            <div className="stat-item">
              <div className="stat-number">{attendanceCount}</div>
              <div className="stat-label">Days Present</div>
            </div>
            <div className="stat-divider"></div>
            <div className="stat-item">
              <div className="stat-number">{leaveCount}</div>
              <div className="stat-label">Leaves Taken</div>
            </div>
            <div className="stat-divider"></div>
            <div className="stat-item">
              <div className="stat-number">{salaryCount}</div>
              <div className="stat-label">Salary Records</div>
            </div>
          </div>
        </div>

        {/* Right Column - Details */}
        <div className="details-section">
          <div className="details-card">
            <div className="card-header">
              <h3>Personal Information</h3>
              <span className="verified-badge">Verified</span>
            </div>

            <div className="details-grid">
              <div className="detail-row">
                <span className="detail-label">Full Name</span>
                <span className="detail-value">{employee?.full_name || "N/A"}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Email Address</span>
                <span className="detail-value">{employee?.email || "N/A"}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Phone Number</span>
                <span className="detail-value">{employee?.phone || "N/A"}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Job Title</span>
                <span className="detail-value">{employee?.job_title || "N/A"}</span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Join Date</span>
                <span className="detail-value">
                  {employee?.join_date ? new Date(employee.join_date).toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric'
                  }) : "N/A"}
                </span>
              </div>
              <div className="detail-row">
                <span className="detail-label">Last Updated</span>
                <span className="detail-value">
                  {new Date().toLocaleDateString('en-US', { 
                    month: 'long', 
                    day: 'numeric',
                    year: 'numeric'
                  })}
                </span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="action-grid">
            <button className="action-btn" onClick={() => router.push("/employees/attendance")}>
              <span className="action-icon">📅</span>
              View Attendance
            </button>
            <button className="action-btn" onClick={() => router.push("/employees/leaves")}>
              <span className="action-icon">🌴</span>
              Apply Leave
            </button>
            <button className="action-btn" onClick={() => router.push("/employees/payslips")}>
              <span className="action-icon">💰</span>
              View Payslips
            </button>
            <button className="action-btn" onClick={generateBioData}>
              <span className="action-icon">📄</span>
              Download Bio Data
            </button>
          </div>
        </div>
      </div>

      <style jsx>{`
        .profile-page {
          min-height: 100vh;
          background-color: #f5f7fa;
          padding: 2rem;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
        }

        /* Header */
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
          padding-bottom: 1rem;
          border-bottom: 2px solid #d0d0d0;
        }

        .page-title {
          font-size: 1.75rem;
          font-weight: 600;
          color: #1e293b;
          margin: 0 0 0.25rem 0;
        }

        .page-subtitle {
          color: #64748b;
          font-size: 0.9rem;
          margin: 0;
        }

        .back-btn {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.5rem 1.25rem;
          background-color: white;
          border: 1px solid #d0d0d0;
          border-radius: 8px;
          color: #1e293b;
          font-size: 0.9rem;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
        }

        .back-btn:hover {
          background-color: #f8fafc;
          border-color: #2563eb;
        }

        .btn-icon {
          width: 16px;
          height: 16px;
        }

        /* Profile Container */
        .profile-container {
          display: grid;
          grid-template-columns: 320px 1fr;
          gap: 1.5rem;
        }

        /* Profile Card */
        .profile-card {
          background: white;
          border: 2px solid #d0d0d0;
          border-radius: 16px;
          padding: 1.5rem;
          text-align: center;
        }

        .avatar-section {
          display: flex;
          justify-content: center;
          margin-bottom: 1rem;
        }

        .avatar {
          width: 90px;
          height: 90px;
          background: linear-gradient(135deg, #2563eb, #1e40af);
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-size: 2.2rem;
          font-weight: 600;
          border: 2px solid #d0d0d0;
        }

        .name {
          font-size: 1.3rem;
          font-weight: 600;
          color: #1e293b;
          margin: 0 0 0.25rem 0;
        }

        .role {
          color: #64748b;
          font-size: 0.9rem;
          margin: 0 0 1.25rem 0;
        }

        .info-items {
          border-top: 2px solid #d0d0d0;
          border-bottom: 2px solid #d0d0d0;
          padding: 1rem 0;
          margin-bottom: 1.25rem;
        }

        .info-item {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 0.5rem 0;
          border-bottom: 1px solid #e0e0e0;
        }

        .info-item:last-child {
          border-bottom: none;
        }

        .info-label {
          color: #64748b;
          font-size: 0.85rem;
        }

        .info-value {
          color: #1e293b;
          font-weight: 500;
          font-size: 0.9rem;
        }

        .status-active {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          color: #0f973d;
        }

        .status-dot {
          width: 8px;
          height: 8px;
          background: #0f973d;
          border-radius: 50%;
        }

        /* Stats Line */
        .stats-line {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 1rem;
          border-top: 2px solid #d0d0d0;
          padding-top: 1rem;
        }

        .stat-item {
          flex: 1;
          text-align: center;
        }

        .stat-number {
          font-size: 1.5rem;
          font-weight: 700;
          color: #2563eb;
          line-height: 1.2;
        }

        .stat-label {
          color: #64748b;
          font-size: 0.75rem;
          text-transform: uppercase;
          letter-spacing: 0.3px;
        }

        .stat-divider {
          width: 1px;
          height: 35px;
          background-color: #d0d0d0;
        }

        /* Details Section */
        .details-section {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .details-card {
          background: white;
          border: 2px solid #d0d0d0;
          border-radius: 16px;
          padding: 1.5rem;
        }

        .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1.5rem;
          padding-bottom: 1rem;
          border-bottom: 2px solid #d0d0d0;
        }

        .card-header h3 {
          font-size: 1.1rem;
          font-weight: 600;
          color: #1e293b;
          margin: 0;
        }

        .verified-badge {
          background: #ecfdf5;
          color: #0f973d;
          padding: 0.25rem 0.75rem;
          border-radius: 20px;
          font-size: 0.75rem;
          font-weight: 500;
          border: 1px solid #d0d0d0;
        }

        .details-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 1.25rem;
        }

        .detail-row {
          display: flex;
          flex-direction: column;
          gap: 0.4rem;
        }

        .detail-label {
          color: #64748b;
          font-size: 0.75rem;
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 0.3px;
        }

        .detail-value {
          color: #1e293b;
          font-size: 0.95rem;
          font-weight: 500;
          padding: 0.3rem 0;
          border-bottom: 1px solid #d0d0d0;
        }

        /* Action Grid */
        .action-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 1rem;
        }

        .action-btn {
          background: white;
          border: 1px solid #d0d0d0;
          border-radius: 10px;
          padding: 0.8rem;
          color: #1e293b;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 0.5rem;
          font-size: 0.85rem;
          font-weight: 500;
          transition: all 0.2s;
        }

        .action-btn:hover {
          background: #f8fafc;
          border-color: #2563eb;
          color: #2563eb;
        }

        .action-icon {
          font-size: 1rem;
        }

        /* Responsive */
        @media (max-width: 1024px) {
          .profile-container {
            grid-template-columns: 1fr;
          }

          .details-grid {
            grid-template-columns: 1fr;
          }

          .action-grid {
            grid-template-columns: repeat(2, 1fr);
          }
        }

        @media (max-width: 768px) {
          .profile-page {
            padding: 1rem;
          }

          .header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }

          .stats-line {
            flex-wrap: wrap;
          }

          .action-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  );
}